=== FrancescoLindiner/ProgettoWSDA/src/main/resources/static/palinsesto.dtd
<!ELEMENT palinsesto (elemento+)>
        <!ELEMENT elemento (file, id)>
        <!ATTLIST elemento durata CDATA #REQUIRED>
        <!ELEMENT file (#PCDATA)>
        <!ELEMENT id (#PCDATA)>

=== FrancescoLindiner/ProgettoWSDA/src/main/resources/static/file_xml/palinsesto1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palinsesto SYSTEM "../palinsesto.dtd">
<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../palinsesto.xsd">
    <elemento durata="15">
        <file>../../file_html/caffe.html</file>
        <id>C1</id>
    </elemento>
    <elemento durata="10">
        <file>../../file_html/coca_cola.html</file>
        <id>C2</id>
    </elemento>
    <elemento durata="15">
        <file>../../file_html/concessionaria.html</file>
        <id>C3</id>
    </elemento>
    <elemento durata="20">
        <file>../../file_html/serieTV.html</file>
        <id>C6</id>
    </elemento>
    <elemento durata="15">
        <file>../../file_html/sushi.html</file>
        <id>C7</id>
    </elemento>
</palinsesto>

=== FrancescoLindiner/ProgettoWSDA/src/main/resources/static/file_xml/palinsesto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palinsesto SYSTEM "../palinsesto.dtd">
<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../palinsesto.xsd">
    <elemento durata="25">
        <file>../../file_html/voli.html</file>
        <id>C10</id>
    </elemento>
    <elemento durata="10">
        <file>../../file_html/telefoni.html</file>
        <id>C08</id>
    </elemento>
    <elemento durata="20">
        <file>../../file_html/pneumatici.html</file>
        <id>C04</id>
    </elemento>
    <elemento durata="20">
        <file>../../file_html/vestiti.html</file>
        <id>C09</id>
    </elemento>
    <elemento durata="15">
        <file>../../file_html/scarpe.html</file>
        <id>C05</id>
    </elemento>
</palinsesto>
